apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blinko

resources:
  - namespace.yaml
  - blinko-website-deployment.yaml
  - blinko-website-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
